"""Seed the dev database with a test learner, segments, and paraphrases.

Run via:

    docker compose run --rm gateway python -m scripts.seed

Idempotent: re-running it will not duplicate rows (uses fixed UUIDs).
Uploads a tiny placeholder blob to MinIO for each segment so `segment.play`
can mint a signed URL. Real audio assets can overwrite the same keys later.

Paraphrase embeddings are generated by calling the analysis service at
`/internal/embed_texts` — in `USE_MOCKS=1` mode this returns deterministic
hash-based vectors so the seed works without the multilingual-e5 weights.
"""

from __future__ import annotations

import asyncio
import os
from uuid import UUID, uuid5, NAMESPACE_URL

import httpx
from sqlalchemy import select

from app.db import sessionmaker_factory
from app.models.tables import LearnerRow, ParaphraseEmbeddingRow, SegmentRow
from app.storage import _bucket, _client, ensure_bucket

ANALYSIS_URL = os.getenv("ANALYSIS_URL", "http://analysis:8001")

# Fixed UUIDs so re-runs are idempotent and the operator dashboard can paste
# the learner_id verbatim.
LEARNER_ID = UUID("00000000-0000-0000-0000-000000000001")

SEGMENTS: list[dict] = [
    {
        "id": UUID("11111111-1111-1111-1111-000000000001"),
        "source_text": "We need to coordinate the delivery schedule with the supply battalion.",
        "source_lang": "en",
        "target_lang": "ko",
        "register": "formal-military",
        "domain": "logistics",
        "difficulty_level": 3,
        "paraphrases": [
            "Delivery timing must be aligned with the supply battalion.",
            "We have to sync the delivery calendar with supply.",
        ],
    },
    {
        "id": UUID("11111111-1111-1111-1111-000000000002"),
        "source_text": "보급 대대와 배송 일정을 조율해야 합니다.",
        "source_lang": "ko",
        "target_lang": "en",
        "register": "formal-military",
        "domain": "logistics",
        "difficulty_level": 4,
        "paraphrases": [
            "보급 대대와 배송 시간을 맞춰야 합니다.",
            "보급 부대와 일정을 조정할 필요가 있습니다.",
        ],
    },
    {
        "id": UUID("11111111-1111-1111-1111-000000000003"),
        "source_text": "The convoy will depart at zero-six-hundred, weather permitting.",
        "source_lang": "en",
        "target_lang": "ko",
        "register": "formal-military",
        "domain": "logistics",
        "difficulty_level": 5,
        "paraphrases": [
            "If the weather holds, the convoy moves at 0600.",
            "The motorcade is set to leave at six in the morning, weather allowing.",
        ],
    },
    {
        "id": UUID("11111111-1111-1111-1111-000000000004"),
        "source_text": "차량 행렬은 날씨가 허락한다면 0600시에 출발할 예정입니다.",
        "source_lang": "ko",
        "target_lang": "en",
        "register": "formal-military",
        "domain": "logistics",
        "difficulty_level": 6,
        "paraphrases": [
            "기상 여건이 허락되면 차량 행렬은 0600시에 출발합니다.",
            "날씨만 괜찮다면 06시에 차량 대열이 떠납니다.",
        ],
    },
    {
        "id": UUID("11111111-1111-1111-1111-000000000005"),
        "source_text": "Diplomatic relations between the two states have entered a new phase.",
        "source_lang": "en",
        "target_lang": "ko",
        "register": "formal-diplomatic",
        "domain": "diplomacy",
        "difficulty_level": 5,
        "paraphrases": [
            "Ties between the two countries are now in a new stage.",
            "A fresh chapter has opened in the two states' diplomacy.",
        ],
    },
]


EMBEDDING_DIM = 1024

# Hardcoded paraphrases per segment (source text first, then alternatives).
# These are intentionally human-written; real production embeddings come from
# the analysis service after first playback.
PARAPHRASES: dict[UUID, list[str]] = {
    UUID("11111111-1111-1111-1111-000000000001"): [
        "We need to coordinate the delivery schedule with the supply battalion.",
        "Delivery timing must be aligned with the supply battalion.",
        "We should sync our delivery plan with the logistics battalion.",
        "Coordination with the supply unit on delivery schedules is required.",
    ],
    UUID("11111111-1111-1111-1111-000000000002"): [
        "보급 대대와 배송 일정을 조율해야 합니다.",
        "보급 부대와 납품 일정을 맞춰야 합니다.",
        "보급 대대에 배송 일정 조율을 요청해야 합니다.",
        "보급 대대와 물자 수송 스케줄을 협의해야 합니다.",
    ],
    UUID("11111111-1111-1111-1111-000000000003"): [
        "The convoy will depart at zero-six-hundred, weather permitting.",
        "The vehicle convoy is scheduled to leave at 0600, contingent on weather.",
        "Departure is set for 0600 hours if conditions allow.",
        "The convoy departs at six hundred hours, assuming favorable weather.",
    ],
    UUID("11111111-1111-1111-1111-000000000004"): [
        "차량 행렬은 날씨가 허락한다면 0600시에 출발할 예정입니다.",
        "날씨 조건이 맞으면 호송 차량은 0600시에 출발합니다.",
        "기상 상황이 허락하는 경우 차량대는 06시에 출발 예정입니다.",
        "호송대는 날씨 여건에 따라 0600시 출발을 계획하고 있습니다.",
    ],
    UUID("11111111-1111-1111-1111-000000000005"): [
        "Diplomatic relations between the two states have entered a new phase.",
        "The bilateral relationship has moved into a new stage of diplomacy.",
        "A new chapter has begun in the diplomatic ties between the two countries.",
        "Relations between the two nations have transitioned to a new diplomatic phase.",
    ],
}


def _random_unit_vector(dim: int, rng: random.Random) -> list[float]:
    """Return a random unit vector of the given dimension."""
    raw = [rng.gauss(0.0, 1.0) for _ in range(dim)]
    norm = math.sqrt(sum(x * x for x in raw))
    return [x / norm for x in raw]


async def _seed_paraphrases() -> None:
    """Insert paraphrase embeddings for each seeded segment.

    Uses deterministic random unit vectors (seeded per segment UUID) so
    re-runs are idempotent in terms of which vectors are generated.
    Real embeddings (from sentence-transformers multilingual-e5-large) are
    written by the analysis service on first segment playback.
    """
    sm = sessionmaker_factory()
    async with sm() as db:
        for seg_id, paraphrases in PARAPHRASES.items():
            seg = (
                await db.execute(select(SegmentRow).where(SegmentRow.id == seg_id))
            ).scalar_one_or_none()
            if seg is None:
                print(f"  segment {seg_id} not found — run upsert_rows first")
                continue

            existing_count = len(
                (
                    await db.execute(
                        select(ParaphraseEmbeddingRow).where(
                            ParaphraseEmbeddingRow.segment_id == seg_id
                        )
                    )
                )
                .scalars()
                .all()
            )
            if existing_count > 0:
                print(f"  paraphrases for {seg_id} already seeded ({existing_count} rows)")
                continue

            # Seed the RNG from the segment UUID for reproducibility.
            rng = random.Random(seg_id.int)
            first_id: UUID | None = None
            for text in paraphrases:
                emb_row = ParaphraseEmbeddingRow(
                    segment_id=seg_id,
                    paraphrase=text,
                    embedding=_random_unit_vector(EMBEDDING_DIM, rng),
                )
                db.add(emb_row)
                await db.flush()
                if first_id is None:
                    first_id = emb_row.id

            if first_id is not None and seg.embedding_id is None:
                seg.embedding_id = first_id

            print(
                f"  inserted {len(paraphrases)} paraphrase embeddings for segment {seg_id}"
            )

        await db.commit()


def _placeholder_blob() -> bytes:
    """Tiny WebM-ish placeholder. Enough that MinIO stores it and presigned
    URLs work; not a real playable file. Overwrite with real audio later."""
    ebml = bytes.fromhex("1a45dfa39f4286810142f7810142f2810442f3810842")
    return ebml + b"\x00" * 256


def segment_audio_key(segment_id: UUID) -> str:
    return f"segments/{segment_id}.webm"


def upload_placeholders() -> None:
    ensure_bucket()
    client = _client()
    bucket = _bucket()
    blob = _placeholder_blob()
    for seg in SEGMENTS:
        key = segment_audio_key(seg["id"])
        client.put_object(Bucket=bucket, Key=key, Body=blob, ContentType="audio/webm")
        print(f"  uploaded {key} ({len(blob)} bytes)")


async def upsert_rows() -> None:
    sm = sessionmaker_factory()
    async with sm() as db:
        existing = await db.execute(
            select(LearnerRow).where(LearnerRow.id == LEARNER_ID)
        )
        if existing.scalar_one_or_none() is None:
            db.add(
                LearnerRow(
                    id=LEARNER_ID,
                    display_name="Dev Learner",
                    primary_lang="ko",
                )
            )
            print(f"  inserted learner {LEARNER_ID}")
        else:
            print(f"  learner {LEARNER_ID} already exists")

        for seg in SEGMENTS:
            existing = await db.execute(
                select(SegmentRow).where(SegmentRow.id == seg["id"])
            )
            if existing.scalar_one_or_none() is None:
                db.add(
                    SegmentRow(
                        id=seg["id"],
                        source_text=seg["source_text"],
                        source_lang=seg["source_lang"],
                        target_lang=seg["target_lang"],
                        register=seg["register"],
                        domain=seg["domain"],
                        difficulty_level=seg["difficulty_level"],
                        audio_path=segment_audio_key(seg["id"]),
                    )
                )
                print(
                    f"  inserted segment {seg['id']} "
                    f"({seg['domain']}/L{seg['difficulty_level']})"
                )
            else:
                print(f"  segment {seg['id']} already exists")

        await db.commit()


def _paraphrase_uuid(segment_id: UUID, idx: int, text: str) -> UUID:
    """Deterministic UUID so re-seeding doesn't insert duplicates."""
    return uuid5(NAMESPACE_URL, f"paraphrase:{segment_id}:{idx}:{text}")


async def _embed(texts: list[str]) -> list[list[float]]:
    """Call the analysis service for embeddings. Falls back to skipping the
    paraphrase seed if analysis isn't reachable — the picker tolerates an
    empty paraphrase table.
    """
    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            r = await client.post(
                f"{ANALYSIS_URL}/internal/embed_texts", json={"texts": texts}
            )
            r.raise_for_status()
            return r.json()["embeddings"]
    except Exception as exc:  # noqa: BLE001
        print(f"  warning: embedding call failed ({exc}); skipping paraphrases")
        return []


async def upsert_paraphrases() -> None:
    sm = sessionmaker_factory()
    async with sm() as db:
        for seg in SEGMENTS:
            texts = [seg["source_text"], *seg["paraphrases"]]
            embeddings = await _embed(texts)
            if not embeddings:
                continue
            for idx, (text, vector) in enumerate(zip(texts, embeddings, strict=True)):
                pid = _paraphrase_uuid(seg["id"], idx, text)
                existing = (
                    await db.execute(
                        select(ParaphraseEmbeddingRow).where(
                            ParaphraseEmbeddingRow.id == pid
                        )
                    )
                ).scalar_one_or_none()
                if existing is not None:
                    continue
                db.add(
                    ParaphraseEmbeddingRow(
                        id=pid,
                        segment_id=seg["id"],
                        paraphrase=text,
                        embedding=vector,
                    )
                )
            print(
                f"  paraphrases for {seg['id']}: {len(texts)} rows queued"
            )
        await db.commit()


async def main() -> None:
    print("Uploading placeholder audio to MinIO...")
    upload_placeholders()
    print("Upserting DB rows...")
    await upsert_rows()
    print("Seeding paraphrases + embeddings...")
    await upsert_paraphrases()
    print()
    print("Done.")
    print(f"  learner_id: {LEARNER_ID}")
    print("  domains: logistics, diplomacy")
    print("  difficulty levels: 3, 4, 5, 6")


if __name__ == "__main__":
    asyncio.run(main())
