#!/usr/bin/env tsx
/**
 * Reads contracts/contracts.json (jsonc) and emits frontend/lib/contracts.ts.
 * Run: npm run gen-contracts
 * DO NOT manually edit frontend/lib/contracts.ts — it is auto-generated.
 */

import * as fs from "fs";
import * as path from "path";

const contractsPath = path.resolve(__dirname, "../../contracts/contracts.json");
const outputPath = path.resolve(__dirname, "../lib/contracts.ts");

// Strip jsonc comments before parsing
function stripJsoncComments(src: string): string {
  return src.replace(/\/\/[^\n]*/g, "").replace(/\/\*[\s\S]*?\*\//g, "");
}

const raw = fs.readFileSync(contractsPath, "utf-8");
const stripped = stripJsoncComments(raw);
const schema = JSON.parse(stripped);

const SESSION_STATES =
  '"idle" | "listening" | "recording" | "analyzing" | "feedback" | "next_segment" | "complete"';
const REGISTER = '"formal-military" | "formal-diplomatic" | "informal"';
const LANG = '"ko" | "en"';
const HEALTH_STATUS = '"ok" | "degraded" | "down"';
const COGNITIVE_LOAD = '"low" | "moderate" | "high" | "overloaded"';
const ERROR_TYPE =
  '"semantic_drift" | "lexical_gap" | "register_error" | "omission" | "tense_shift" | "precision_loss"';
const SEVERITY = '"minor" | "moderate" | "critical"';
const FOLLOWUP_TYPE = '"repeat" | "rephrase" | "drill_term" | "contextual_qa"';
const MASTERY_TRIGGERED = '"prosody" | "semantic" | "both"';
const WS_ERROR_CODE =
  '"invalid_state" | "invalid_payload" | "upload_failed" | "analysis_failed" | "internal"';

const header = `// AUTO-GENERATED by scripts/gen-contracts.ts — DO NOT EDIT MANUALLY.
// Source of truth: contracts/contracts.json (version ${schema._meta.version})
// Generated at: ${new Date().toISOString()}

`;

const body = `
export interface AudioSubmission {
  segment_id: string;
  attempt_id: string;
  audio_format: "opus/webm";
  /** delivered in the following binary frame */
  audio_blob?: never;
  byte_length: number;
  duration_ms: number;
  recorded_at: string;
}

export interface AnalysisRequest {
  attempt_id: string;
  segment_id: string;
  session_id: string;
  learner_id: string;
  audio_path: string;
  source_text: string;
  source_lang: ${LANG};
  target_lang: ${LANG};
  register: ${REGISTER};
  domain: string;
  difficulty_level: number;
  enqueued_at: string;
}

export interface ProsodyResult {
  attempt_id: string;
  pause_count: number;
  filler_count: number;
  mean_wpm: number;
  silence_ratio: number;
  cognitive_load_estimate: ${COGNITIVE_LOAD};
  feedback_audio_path: string;
  computed_at: string;
  latency_ms: number;
}

export interface SemanticError {
  type: ${ERROR_TYPE};
  source_span: string;
  user_span: string | null;
  severity: ${SEVERITY};
  explanation: string;
}

export interface FollowupExercise {
  type: ${FOLLOWUP_TYPE};
  prompt_text: string;
  prompt_audio_path: string;
}

export interface SemanticResult {
  attempt_id: string;
  transcript: string;
  reference_translation: string;
  acceptable_paraphrases: string[];
  errors: SemanticError[];
  overall_score: number;
  feedback_text: string;
  feedback_audio_path: string;
  followup_exercise: FollowupExercise;
  computed_at: string;
  latency_ms: number;
}

export interface MasteryUpdate {
  learner_id: string;
  segment_id: string;
  domain: string;
  old_mastery: number;
  new_mastery: number;
  difficulty_delta: number;
  triggered_by: ${MASTERY_TRIGGERED};
  computed_at: string;
}

export interface Learner {
  id: string;
  display_name: string;
  primary_lang: ${LANG};
  created_at: string;
}

export type SessionState = ${SESSION_STATES};

export interface Session {
  id: string;
  learner_id: string;
  state: SessionState;
  domain: string;
  target_lang: ${LANG};
  source_lang: ${LANG};
  started_at: string;
  completed_at: string | null;
  segment_count: number;
  current_segment_id: string | null;
}

export interface Segment {
  id: string;
  source_text: string;
  source_lang: ${LANG};
  target_lang: ${LANG};
  register: ${REGISTER};
  domain: string;
  difficulty_level: number;
  audio_path: string;
  embedding_id: string | null;
  created_at: string;
}

export interface Attempt {
  id: string;
  session_id: string;
  segment_id: string;
  learner_id: string;
  audio_path: string;
  recorded_at: string;
  prosody_result: ProsodyResult | null;
  semantic_result: SemanticResult | null;
  closed_at: string | null;
}

export interface MasteryScore {
  learner_id: string;
  domain: string;
  mastery: number;
  attempts_count: number;
  last_attempt_at: string;
  updated_at: string;
}

// ---- REST shapes ----

export interface PostSessionRequest {
  learner_id: string;
  domain: string;
  source_lang: ${LANG};
  target_lang: ${LANG};
}

export type PostSessionResponse = Session;
export type GetSessionResponse = Session;

export interface CompleteSessionResponse {
  session: Session;
  attempts_count: number;
  mean_score: number;
  mastery_changes: MasteryUpdate[];
}

export type GetLearnerResponse = Learner;

export interface GetLearnerMasteryResponse {
  learner_id: string;
  scores: MasteryScore[];
}

export interface HealthResponse {
  status: ${HEALTH_STATUS};
  version: string;
  checked_at: string;
  dependencies: {
    postgres: "ok" | "down";
    redis: "ok" | "down";
    minio: "ok" | "down";
  };
}

// ---- WebSocket envelope ----

export interface WSEnvelope<T = unknown> {
  type: string;
  ts: string;
  payload: T;
}

// ---- WS Client → Server ----

export interface WSSessionStart {
  type: "session.start";
  ts: string;
  payload: { session_id: string };
}

export interface WSSegmentRequest {
  type: "segment.request";
  ts: string;
  payload: { session_id: string };
}

export interface WSRecordingBegin {
  type: "recording.begin";
  ts: string;
  payload: { session_id: string; segment_id: string; attempt_id: string };
}

export interface WSAudioSubmitHeader {
  type: "audio.submit_header";
  ts: string;
  payload: AudioSubmission;
}

export interface WSSessionComplete {
  type: "session.complete";
  ts: string;
  payload: { session_id: string };
}

// ---- WS Server → Client ----

export interface WSSegmentPlay {
  type: "segment.play";
  ts: string;
  payload: {
    segment_id: string;
    audio_url: string;
    duration_ms: number;
    difficulty_level: number;
    delay_ms: number;
  };
}

export interface WSAudioAck {
  type: "audio.ack";
  ts: string;
  payload: { attempt_id: string; audio_path: string };
}

export interface WSProsodyResult {
  type: "prosody.result";
  ts: string;
  payload: ProsodyResult;
}

export interface WSSemanticResult {
  type: "semantic.result";
  ts: string;
  payload: SemanticResult;
}

export interface WSMasteryUpdate {
  type: "mastery.update";
  ts: string;
  payload: MasteryUpdate;
}

export interface WSSessionCompleteAck {
  type: "session.complete_ack";
  ts: string;
  payload: { session_id: string; attempts_count: number; mean_score: number };
}

export interface WSStateChange {
  type: "state.change";
  ts: string;
  payload: {
    session_id: string;
    from: SessionState;
    to: SessionState;
    reason: string;
  };
}

export interface WSError {
  type: "error";
  ts: string;
  payload: {
    code: ${WS_ERROR_CODE};
    detail: string;
    attempt_id: string | null;
    session_id: string | null;
  };
}

export type ServerMessage =
  | WSSegmentPlay
  | WSAudioAck
  | WSProsodyResult
  | WSSemanticResult
  | WSMasteryUpdate
  | WSSessionCompleteAck
  | WSStateChange
  | WSError;

export type ClientMessage =
  | WSSessionStart
  | WSSegmentRequest
  | WSRecordingBegin
  | WSAudioSubmitHeader
  | WSSessionComplete;
`;

fs.writeFileSync(outputPath, header + body, "utf-8");
console.log(`Generated ${outputPath}`);
