#!/usr/bin/env tsx
/**
 * Reads contracts/contracts.json (jsonc) and emits frontend/lib/contracts.ts.
 *
 * The generator is hand-maintained alongside the JSON: when a contract
 * changes, edit BOTH `contracts/contracts.json` and the template in this
 * file in the same commit. Run `npm run gen-contracts` to regenerate.
 *
 * DO NOT manually edit frontend/lib/contracts.ts — it is auto-generated.
 *
 * The script also performs a sanity check: every top-level shape in
 * `contracts.json` (excluding `_meta`) must appear by name in the
 * emitted body. If a JSON shape has no matching `export interface` /
 * `export type` block here, the script exits non-zero so the drift is
 * caught at CI time.
 */

import * as fs from "fs";
import * as path from "path";

const contractsPath = path.resolve(__dirname, "../../contracts/contracts.json");
const outputPath = path.resolve(__dirname, "../lib/contracts.ts");

// Strip jsonc comments before parsing
function stripJsoncComments(src: string): string {
  return src.replace(/\/\/[^\n]*/g, "").replace(/\/\*[\s\S]*?\*\//g, "");
}

const raw = fs.readFileSync(contractsPath, "utf-8");
const stripped = stripJsoncComments(raw);
const schema = JSON.parse(stripped);

// Common string-literal unions reused throughout the body.
const SESSION_STATES =
  '"idle" | "listening" | "recording" | "analyzing" | "feedback" | "next_segment" | "complete"';
const REGISTER = '"formal-military" | "formal-diplomatic" | "informal"';
const LANG = '"ko" | "en"';
const HEALTH_STATUS = '"ok" | "degraded" | "down"';
const COGNITIVE_LOAD = '"low" | "moderate" | "high" | "overloaded"';
const ERROR_TYPE =
  '"semantic_drift" | "lexical_gap" | "register_error" | "omission" | "tense_shift" | "precision_loss"';
const SEVERITY = '"minor" | "moderate" | "critical"';
const FOLLOWUP_TYPE = '"repeat" | "rephrase" | "drill_term" | "contextual_qa"';
const MASTERY_TRIGGERED = '"prosody" | "semantic" | "both"';
const WS_ERROR_CODE =
  '"invalid_state" | "invalid_payload" | "upload_failed" | "analysis_failed" | "internal"';

const header = `// AUTO-GENERATED by scripts/gen-contracts.ts — DO NOT EDIT MANUALLY.
// Source of truth: contracts/contracts.json (version ${schema._meta.version})
// Generated at: ${new Date().toISOString()}

`;

const body = `
export interface AudioSubmission {
  segment_id: string;
  attempt_id: string;
  audio_format: string;
  /** delivered in the following binary frame */
  audio_blob?: never;
  byte_length: number;
  duration_ms: number;
  recorded_at: string;
}

export type SessionMode = "interpretation" | "memorization";

export type KeyPointImportance = "primary" | "secondary";

export interface KeyPoint {
  text: string;
  recalled: boolean;
  importance: KeyPointImportance;
}

export interface AnalysisRequest {
  attempt_id: string;
  segment_id: string;
  session_id: string;
  learner_id: string;
  audio_path: string;
  source_text: string;
  source_lang: ${LANG};
  target_lang: ${LANG};
  register: ${REGISTER};
  domain: string;
  difficulty_level: number;
  enqueued_at: string;
  asr_prompt?: string | null;
  mode?: SessionMode;
}

export interface ProsodyResult {
  attempt_id: string;
  pause_count: number;
  filler_count: number;
  mean_wpm: number;
  silence_ratio: number;
  cognitive_load_estimate: ${COGNITIVE_LOAD};
  feedback_audio_path: string;
  computed_at: string;
  latency_ms: number;
}

export interface SemanticError {
  type: ${ERROR_TYPE};
  source_span: string;
  user_span: string | null;
  severity: ${SEVERITY};
  explanation: string;
}

export interface FollowupExercise {
  type: ${FOLLOWUP_TYPE};
  prompt_text: string;
  prompt_audio_path: string;
}

export interface SemanticResult {
  attempt_id: string;
  mode: SessionMode;
  source_text: string;
  transcript: string;
  reference_translation: string;
  acceptable_paraphrases: string[];
  errors: SemanticError[];
  key_points: KeyPoint[] | null;
  overall_score: number;
  feedback_text: string;
  feedback_audio_path: string;
  followup_exercise: FollowupExercise;
  computed_at: string;
  latency_ms: number;
}

export interface MasteryUpdate {
  learner_id: string;
  segment_id: string;
  domain: string;
  old_mastery: number;
  new_mastery: number;
  difficulty_delta: number;
  triggered_by: ${MASTERY_TRIGGERED};
  computed_at: string;
}

export interface Learner {
  id: string;
  display_name: string;
  primary_lang: ${LANG};
  created_at: string;
}

export type SessionState = ${SESSION_STATES};

export interface Session {
  id: string;
  learner_id: string;
  mode: SessionMode;
  state: SessionState;
  domain: string;
  target_lang: ${LANG};
  source_lang: ${LANG};
  started_at: string;
  completed_at: string | null;
  segment_count: number;
  replays_budget: number;
  current_segment_id: string | null;
}

export interface Segment {
  id: string;
  source_text: string;
  source_lang: ${LANG};
  target_lang: ${LANG};
  register: ${REGISTER};
  domain: string;
  difficulty_level: number;
  audio_path: string;
  embedding_id: string | null;
  created_at: string;
}

export interface Attempt {
  id: string;
  session_id: string;
  segment_id: string;
  learner_id: string;
  audio_path: string;
  recorded_at: string;
  prosody_result: ProsodyResult | null;
  semantic_result: SemanticResult | null;
  replayed: boolean;
  closed_at: string | null;
}

export interface MasteryScore {
  learner_id: string;
  domain: string;
  mastery: number;
  tier: number;
  tier_name: string;
  next_tier_name: string | null;
  progress: number;
  attempts_count: number;
  last_attempt_at: string;
  updated_at: string;
}

// ---- REST shapes ----

export interface GenerationParams {
  topics: string[];
  user_level: 1 | 2 | 3 | 4 | 5;
  duration: "short" | "medium" | "long";
  current_context?: string | null;
  n?: number;
}

export interface PostSessionRequest {
  learner_id: string;
  domain: string;
  source_lang: ${LANG};
  target_lang: ${LANG};
  mode?: SessionMode;
  generation?: GenerationParams | null;
}

export type PostSessionResponse = Session;
export type GetSessionResponse = Session;

export interface CompleteSessionResponse {
  session: Session;
  attempts_count: number;
  mean_score: number;
  mastery_changes: MasteryUpdate[];
}

export interface GetAttemptAudioUrlResponse {
  audio_url: string;
  expires_in_s: number;
}

export type GetLearnerResponse = Learner;

export interface GetLearnerMasteryResponse {
  learner_id: string;
  scores: MasteryScore[];
}

export interface HealthResponse {
  status: ${HEALTH_STATUS};
  version: string;
  checked_at: string;
  dependencies: {
    postgres: "ok" | "down";
    redis: "ok" | "down";
    minio: "ok" | "down";
  };
}

// ---- WebSocket envelope ----

export interface WSEnvelope<T = unknown> {
  type: string;
  ts: string;
  payload: T;
}

// ---- WS Client → Server ----

export interface WSSessionStart {
  type: "session.start";
  ts: string;
  payload: { session_id: string };
}

export interface WSSegmentRequest {
  type: "segment.request";
  ts: string;
  payload: { session_id: string };
}

export interface WSRecordingBegin {
  type: "recording.begin";
  ts: string;
  payload: { session_id: string; segment_id: string; attempt_id: string };
}

export interface WSAudioSubmitHeader {
  type: "audio.submit_header";
  ts: string;
  payload: AudioSubmission;
}

export interface WSSessionComplete {
  type: "session.complete";
  ts: string;
  payload: { session_id: string };
}

// ---- WS Server → Client ----

export interface WSSegmentPlay {
  type: "segment.play";
  ts: string;
  payload: {
    segment_id: string;
    audio_url: string;
    duration_ms: number;
    difficulty_level: number;
    delay_ms: number;
  };
}

export interface WSAudioAck {
  type: "audio.ack";
  ts: string;
  payload: { attempt_id: string; audio_path: string };
}

export interface WSProsodyResult {
  type: "prosody.result";
  ts: string;
  payload: ProsodyResult;
}

export interface WSSemanticResult {
  type: "semantic.result";
  ts: string;
  payload: SemanticResult;
}

export interface WSMasteryUpdate {
  type: "mastery.update";
  ts: string;
  payload: MasteryUpdate;
}

export interface WSSessionCompleteAck {
  type: "session.complete_ack";
  ts: string;
  payload: { session_id: string; attempts_count: number; mean_score: number };
}

export interface WSStateChange {
  type: "state.change";
  ts: string;
  payload: {
    session_id: string;
    from: SessionState;
    to: SessionState;
    reason: string;
  };
}

export interface WSGenerationProgress {
  type: "generation.progress";
  ts: string;
  payload: {
    session_id: string;
    ready: number;
    target: number;
    state: "pending" | "ready" | "failed";
  };
}

export interface WSGenerationComplete {
  type: "generation.complete";
  ts: string;
  payload: {
    session_id: string;
    count: number;
    scenario_summary: string | null;
  };
}

export type ReplayDeniedReason =
  | "budget_exhausted"
  | "already_replayed"
  | "wrong_mode"
  | "invalid_state";

export interface WSReplayRequest {
  type: "replay.request";
  ts: string;
  payload: { session_id: string; attempt_id: string };
}

export interface WSReplayGranted {
  type: "replay.granted";
  ts: string;
  payload: { session_id: string; attempt_id: string; replays_remaining: number };
}

export interface WSReplayDenied {
  type: "replay.denied";
  ts: string;
  payload: {
    session_id: string;
    attempt_id: string;
    reason: ReplayDeniedReason;
    replays_remaining: number;
  };
}

export interface WSError {
  type: "error";
  ts: string;
  payload: {
    code: ${WS_ERROR_CODE};
    detail: string;
    attempt_id: string | null;
    session_id: string | null;
  };
}

export type ServerMessage =
  | WSSegmentPlay
  | WSAudioAck
  | WSProsodyResult
  | WSSemanticResult
  | WSMasteryUpdate
  | WSSessionCompleteAck
  | WSStateChange
  | WSGenerationProgress
  | WSGenerationComplete
  | WSReplayGranted
  | WSReplayDenied
  | WSError;

export type ClientMessage =
  | WSSessionStart
  | WSSegmentRequest
  | WSRecordingBegin
  | WSAudioSubmitHeader
  | WSReplayRequest
  | WSSessionComplete;
`;

// Sanity check: every JSON top-level shape (excluding the `_meta` block,
// the namespace placeholder `WSMessage.*`, and internal RPC shapes that
// are server-only) must have a matching TypeScript export in the body.
// New shapes added to contracts.json without a corresponding entry here
// would silently drift.
const SERVER_ONLY_SHAPES = new Set([
  "VocabExtractionRequest",
  "VocabExtractionResult",
]);

// Map a JSON shape key (which may be dot-namespaced like "REST.HealthResponse"
// or "WSMessage.SegmentPlay") to the conventional TypeScript export name.
function expectedTsName(jsonKey: string): string {
  if (jsonKey.startsWith("REST.")) return jsonKey.slice("REST.".length);
  if (jsonKey.startsWith("WSMessage.")) return "WS" + jsonKey.slice("WSMessage.".length);
  return jsonKey;
}

const jsonShapes = Object.keys(schema).filter(
  (k) =>
    !k.startsWith("_") &&
    !SERVER_ONLY_SHAPES.has(k) &&
    !k.endsWith(".*") // namespace placeholders
);
const missing: string[] = [];
for (const jsonKey of jsonShapes) {
  const name = expectedTsName(jsonKey);
  // Match `export interface Name<...>`, `export interface Name {`, or
  // `export type Name = ...`. Use a regex to be flexible about generics.
  const present = new RegExp(
    `export (interface|type) ${name.replace(/[.*+?^${}()|[\\]\\\\]/g, "\\\\$&")}[\\s<={]`
  ).test(body);
  if (!present) missing.push(`${jsonKey} (expected ${name})`);
}
if (missing.length > 0) {
  console.error(
    "gen-contracts: contracts.json declares shapes not present in the TS template:"
  );
  for (const m of missing) console.error(`  - ${m}`);
  console.error(
    "Add matching exports to the body in scripts/gen-contracts.ts, then re-run."
  );
  process.exit(1);
}

fs.writeFileSync(outputPath, header + body, "utf-8");
console.log(`Generated ${outputPath}`);
console.log(`Covered ${jsonShapes.length} contracts.json shapes.`);
