"""Static vocabulary seeds — ~30 en→ko terms per domain.

UUIDs are deterministic via uuid5 so re-seeding is idempotent.
Each entry seeds the en→ko direction; the seeder can be extended to ko→en
by swapping source_lang/target_lang.
"""

from __future__ import annotations

from uuid import NAMESPACE_URL, UUID, uuid5

TOPIC_SEEDS: dict[str, list[dict]] = {
    "logistics": [
        {"term": "supply chain", "definition": "공급망", "register": "formal-military"},
        {"term": "requisition", "definition": "청구", "register": "formal-military"},
        {"term": "procurement", "definition": "조달", "register": "formal-military"},
        {"term": "inventory", "definition": "재고", "register": "formal-military"},
        {"term": "manifest", "definition": "화물 목록", "register": "formal-military"},
        {"term": "sortie", "definition": "출격", "register": "formal-military"},
        {"term": "airlift", "definition": "공수", "register": "formal-military"},
        {"term": "sealift", "definition": "해상 수송", "register": "formal-military"},
        {"term": "convoy", "definition": "호송대", "register": "formal-military"},
        {"term": "depot", "definition": "보급 창고", "register": "formal-military"},
        {"term": "throughput", "definition": "처리량", "register": "formal-military"},
        {"term": "forward operating base", "definition": "전진 작전 기지", "register": "formal-military"},
        {"term": "distribution hub", "definition": "물류 거점", "register": "formal-military"},
        {"term": "stockpile", "definition": "비축물", "register": "formal-military"},
        {"term": "echelon", "definition": "제대", "register": "formal-military"},
        {"term": "attrition rate", "definition": "소모율", "register": "formal-military"},
        {"term": "lead time", "definition": "조달 소요 시간", "register": "formal-military"},
        {"term": "containerized cargo", "definition": "컨테이너 화물", "register": "formal-military"},
        {"term": "hazardous material", "definition": "위험물", "register": "formal-military"},
        {"term": "load plan", "definition": "적재 계획", "register": "formal-military"},
        {"term": "palletize", "definition": "팔레트에 적재하다", "register": "formal-military"},
        {"term": "retrograde", "definition": "후방 이송", "register": "formal-military"},
        {"term": "sustainment", "definition": "전투 지속 지원", "register": "formal-military"},
        {"term": "cross-leveling", "definition": "횡적 균형 배분", "register": "formal-military"},
        {"term": "pre-positioning", "definition": "사전 배치", "register": "formal-military"},
        {"term": "ammunition", "definition": "탄약", "register": "formal-military"},
        {"term": "fuel resupply", "definition": "연료 재보급", "register": "formal-military"},
        {"term": "medical supplies", "definition": "의료 물자", "register": "formal-military"},
        {"term": "maintenance cycle", "definition": "정비 주기", "register": "formal-military"},
        {"term": "bottleneck", "definition": "병목 현상", "register": "formal-military"},
    ],
    "diplomacy": [
        {"term": "communiqué", "definition": "공동 성명", "register": "formal-diplomatic"},
        {"term": "bilateral", "definition": "양자 간", "register": "formal-diplomatic"},
        {"term": "multilateral", "definition": "다자 간", "register": "formal-diplomatic"},
        {"term": "ratify", "definition": "비준하다", "register": "formal-diplomatic"},
        {"term": "normalization", "definition": "정상화", "register": "formal-diplomatic"},
        {"term": "sanction", "definition": "제재", "register": "formal-diplomatic"},
        {"term": "envoy", "definition": "특사", "register": "formal-diplomatic"},
        {"term": "memorandum of understanding", "definition": "양해각서", "register": "formal-diplomatic"},
        {"term": "sovereignty", "definition": "주권", "register": "formal-diplomatic"},
        {"term": "diplomatic immunity", "definition": "외교적 면책특권", "register": "formal-diplomatic"},
        {"term": "persona non grata", "definition": "기피 인물", "register": "formal-diplomatic"},
        {"term": "treaty", "definition": "조약", "register": "formal-diplomatic"},
        {"term": "ceasefire", "definition": "휴전", "register": "formal-diplomatic"},
        {"term": "armistice", "definition": "정전 협정", "register": "formal-diplomatic"},
        {"term": "demilitarized zone", "definition": "비무장지대", "register": "formal-diplomatic"},
        {"term": "good offices", "definition": "주선", "register": "formal-diplomatic"},
        {"term": "summit", "definition": "정상회담", "register": "formal-diplomatic"},
        {"term": "communiqué draft", "definition": "공동 성명 초안", "register": "formal-diplomatic"},
        {"term": "protocol", "definition": "의정서", "register": "formal-diplomatic"},
        {"term": "annexure", "definition": "부속서", "register": "formal-diplomatic"},
        {"term": "interlocutor", "definition": "대화 상대방", "register": "formal-diplomatic"},
        {"term": "back-channel", "definition": "비공식 채널", "register": "formal-diplomatic"},
        {"term": "détente", "definition": "긴장 완화", "register": "formal-diplomatic"},
        {"term": "rapprochement", "definition": "관계 개선", "register": "formal-diplomatic"},
        {"term": "demarche", "definition": "외교적 항의", "register": "formal-diplomatic"},
        {"term": "consular", "definition": "영사의", "register": "formal-diplomatic"},
        {"term": "ultimatum", "definition": "최후 통첩", "register": "formal-diplomatic"},
        {"term": "provisional agreement", "definition": "잠정 합의", "register": "formal-diplomatic"},
        {"term": "joint declaration", "definition": "공동 선언", "register": "formal-diplomatic"},
        {"term": "observer status", "definition": "참관국 지위", "register": "formal-diplomatic"},
    ],
    "intelligence": [
        {"term": "reconnaissance", "definition": "정찰", "register": "formal-military"},
        {"term": "surveillance", "definition": "감시", "register": "formal-military"},
        {"term": "signals intelligence", "definition": "신호 정보", "register": "formal-military"},
        {"term": "human intelligence", "definition": "인간 정보", "register": "formal-military"},
        {"term": "imagery intelligence", "definition": "영상 정보", "register": "formal-military"},
        {"term": "open-source intelligence", "definition": "공개 출처 정보", "register": "formal-military"},
        {"term": "counterintelligence", "definition": "방첩", "register": "formal-military"},
        {"term": "covert operation", "definition": "비밀 작전", "register": "formal-military"},
        {"term": "asset", "definition": "정보 자산", "register": "formal-military"},
        {"term": "handler", "definition": "담당 공작원", "register": "formal-military"},
        {"term": "cover story", "definition": "위장 신분", "register": "formal-military"},
        {"term": "dead drop", "definition": "비밀 정보 전달 장소", "register": "formal-military"},
        {"term": "tradecraft", "definition": "공작 기술", "register": "formal-military"},
        {"term": "exploitation", "definition": "정보 활용", "register": "formal-military"},
        {"term": "fusion center", "definition": "정보 통합 센터", "register": "formal-military"},
        {"term": "order of battle", "definition": "전투 서열", "register": "formal-military"},
        {"term": "threat assessment", "definition": "위협 평가", "register": "formal-military"},
        {"term": "indicators and warnings", "definition": "징후 및 경보", "register": "formal-military"},
        {"term": "collection plan", "definition": "수집 계획", "register": "formal-military"},
        {"term": "dissemination", "definition": "배포", "register": "formal-military"},
        {"term": "compartmentalization", "definition": "정보 구획화", "register": "formal-military"},
        {"term": "need-to-know", "definition": "지득 필요성", "register": "formal-military"},
        {"term": "classification level", "definition": "비밀 등급", "register": "formal-military"},
        {"term": "red team", "definition": "레드팀", "register": "formal-military"},
        {"term": "deception operation", "definition": "기만 작전", "register": "formal-military"},
        {"term": "exfiltrate", "definition": "비밀 탈출시키다", "register": "formal-military"},
        {"term": "intercept", "definition": "감청", "register": "formal-military"},
        {"term": "electronic warfare", "definition": "전자전", "register": "formal-military"},
        {"term": "targeting cycle", "definition": "표적 선정 주기", "register": "formal-military"},
        {"term": "ground truth", "definition": "실제 상황", "register": "formal-military"},
    ],
    "operations": [
        {"term": "rules of engagement", "definition": "교전 규칙", "register": "formal-military"},
        {"term": "command and control", "definition": "지휘 통제", "register": "formal-military"},
        {"term": "fire support", "definition": "화력 지원", "register": "formal-military"},
        {"term": "close air support", "definition": "근접 항공 지원", "register": "formal-military"},
        {"term": "maneuver", "definition": "기동", "register": "formal-military"},
        {"term": "flank", "definition": "측면", "register": "formal-military"},
        {"term": "envelopment", "definition": "포위 기동", "register": "formal-military"},
        {"term": "perimeter defense", "definition": "주변 방어", "register": "formal-military"},
        {"term": "blocking position", "definition": "차단 진지", "register": "formal-military"},
        {"term": "breach", "definition": "돌파구 개설", "register": "formal-military"},
        {"term": "exploitation phase", "definition": "전과 확대 단계", "register": "formal-military"},
        {"term": "consolidation", "definition": "진지 강화", "register": "formal-military"},
        {"term": "combat power", "definition": "전투력", "register": "formal-military"},
        {"term": "operational tempo", "definition": "작전 속도", "register": "formal-military"},
        {"term": "deconfliction", "definition": "임무 충돌 방지", "register": "formal-military"},
        {"term": "fratricide", "definition": "아군 오사", "register": "formal-military"},
        {"term": "battle rhythm", "definition": "전투 리듬", "register": "formal-military"},
        {"term": "scheme of maneuver", "definition": "기동 구상", "register": "formal-military"},
        {"term": "axis of advance", "definition": "진격 축선", "register": "formal-military"},
        {"term": "phase line", "definition": "단계 통제선", "register": "formal-military"},
        {"term": "checkpoints", "definition": "검문소", "register": "formal-military"},
        {"term": "cordon and search", "definition": "포위 수색", "register": "formal-military"},
        {"term": "direct action", "definition": "직접 행동 임무", "register": "formal-military"},
        {"term": "air assault", "definition": "공중 강습", "register": "formal-military"},
        {"term": "amphibious operation", "definition": "상륙 작전", "register": "formal-military"},
        {"term": "suppression", "definition": "제압", "register": "formal-military"},
        {"term": "objective rally point", "definition": "목표 집결 지점", "register": "formal-military"},
        {"term": "battle handover", "definition": "전투 인계", "register": "formal-military"},
        {"term": "relief in place", "definition": "진지 교대", "register": "formal-military"},
        {"term": "passage of lines", "definition": "부대 통과", "register": "formal-military"},
    ],
    "medical": [
        {"term": "triage", "definition": "부상자 분류", "register": "formal-military"},
        {"term": "medevac", "definition": "의무 후송", "register": "formal-military"},
        {"term": "tourniquet", "definition": "지혈대", "register": "formal-military"},
        {"term": "hemorrhage", "definition": "출혈", "register": "formal-military"},
        {"term": "trauma", "definition": "외상", "register": "formal-military"},
        {"term": "casualty", "definition": "사상자", "register": "formal-military"},
        {"term": "vital signs", "definition": "활력 징후", "register": "formal-military"},
        {"term": "airway management", "definition": "기도 관리", "register": "formal-military"},
        {"term": "field dressing", "definition": "야전 처치", "register": "formal-military"},
        {"term": "burn victim", "definition": "화상 환자", "register": "formal-military"},
        {"term": "blast injury", "definition": "폭발 부상", "register": "formal-military"},
        {"term": "hypothermia", "definition": "저체온증", "register": "formal-military"},
        {"term": "dehydration", "definition": "탈수", "register": "formal-military"},
        {"term": "point of injury", "definition": "부상 지점", "register": "formal-military"},
        {"term": "mass casualty incident", "definition": "대규모 사상자 사건", "register": "formal-military"},
        {"term": "surgical team", "definition": "수술팀", "register": "formal-military"},
        {"term": "forward surgical team", "definition": "전방 수술팀", "register": "formal-military"},
        {"term": "blood transfusion", "definition": "수혈", "register": "formal-military"},
        {"term": "intravenous fluids", "definition": "정맥 수액", "register": "formal-military"},
        {"term": "analgesia", "definition": "진통제", "register": "formal-military"},
        {"term": "sedation", "definition": "진정", "register": "formal-military"},
        {"term": "contamination", "definition": "오염", "register": "formal-military"},
        {"term": "decontamination", "definition": "제독", "register": "formal-military"},
        {"term": "chemical exposure", "definition": "화학물질 노출", "register": "formal-military"},
        {"term": "quarantine", "definition": "격리", "register": "formal-military"},
        {"term": "infectious disease", "definition": "감염병", "register": "formal-military"},
        {"term": "prophylaxis", "definition": "예방 처치", "register": "formal-military"},
        {"term": "orthopaedic injury", "definition": "정형외과적 부상", "register": "formal-military"},
        {"term": "concussion", "definition": "뇌진탕", "register": "formal-military"},
        {"term": "evacuation chain", "definition": "후송 체계", "register": "formal-military"},
    ],
    "cyber": [
        {"term": "intrusion", "definition": "침입", "register": "formal-military"},
        {"term": "malware", "definition": "악성 소프트웨어", "register": "formal-military"},
        {"term": "ransomware", "definition": "랜섬웨어", "register": "formal-military"},
        {"term": "zero-day exploit", "definition": "제로데이 취약점 공격", "register": "formal-military"},
        {"term": "phishing", "definition": "피싱", "register": "formal-military"},
        {"term": "denial of service", "definition": "서비스 거부 공격", "register": "formal-military"},
        {"term": "command-and-control server", "definition": "명령 제어 서버", "register": "formal-military"},
        {"term": "lateral movement", "definition": "수평 이동", "register": "formal-military"},
        {"term": "privilege escalation", "definition": "권한 상승", "register": "formal-military"},
        {"term": "exfiltration", "definition": "데이터 유출", "register": "formal-military"},
        {"term": "patch", "definition": "보안 패치", "register": "formal-military"},
        {"term": "firewall", "definition": "방화벽", "register": "formal-military"},
        {"term": "encryption", "definition": "암호화", "register": "formal-military"},
        {"term": "decryption", "definition": "복호화", "register": "formal-military"},
        {"term": "backdoor", "definition": "백도어", "register": "formal-military"},
        {"term": "supply chain attack", "definition": "공급망 공격", "register": "formal-military"},
        {"term": "social engineering", "definition": "사회공학적 공격", "register": "formal-military"},
        {"term": "threat actor", "definition": "위협 행위자", "register": "formal-military"},
        {"term": "attribution", "definition": "공격 주체 귀속", "register": "formal-military"},
        {"term": "incident response", "definition": "침해 대응", "register": "formal-military"},
        {"term": "forensics", "definition": "디지털 포렌식", "register": "formal-military"},
        {"term": "vulnerability assessment", "definition": "취약점 평가", "register": "formal-military"},
        {"term": "penetration testing", "definition": "침투 테스트", "register": "formal-military"},
        {"term": "critical infrastructure", "definition": "핵심 기반시설", "register": "formal-military"},
        {"term": "air gap", "definition": "에어 갭", "register": "formal-military"},
        {"term": "insider threat", "definition": "내부자 위협", "register": "formal-military"},
        {"term": "offensive cyber operation", "definition": "공세적 사이버 작전", "register": "formal-military"},
        {"term": "defensive cyber operation", "definition": "방어적 사이버 작전", "register": "formal-military"},
        {"term": "cyber resilience", "definition": "사이버 복원력", "register": "formal-military"},
        {"term": "nation-state actor", "definition": "국가 행위자", "register": "formal-military"},
    ],
}


def seed_uuid(domain: str, source_lang: str, term: str) -> UUID:
    return uuid5(NAMESPACE_URL, f"vocab_seed:{domain}:{source_lang}:{term}")


def domain_asr_prompt(domain: str, target_lang: str) -> str:
    """Return a comma-joined hint string of domain vocabulary for Whisper priming.

    When *target_lang* is ``"ko"`` the Korean definitions are used; for ``"en"``
    (or any other value) the English terms are used.  An unknown *domain* returns
    an empty string.
    """
    entries = TOPIC_SEEDS.get(domain)
    if not entries:
        return ""
    if target_lang == "ko":
        return ", ".join(entry["definition"] for entry in entries)
    return ", ".join(entry["term"] for entry in entries)
